# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, default='', max_length=128)),
                ('address_line2', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('county', models.CharField(blank=True, default='', max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('zip_code', models.CharField(blank=True, default='', max_length=8)),
                ('profile_type', models.CharField(blank=True, choices=[('ARTIST', 'Artist'), ('CUSTOMER', 'Customer')], default='', max_length=24)),
                ('phone', models.CharField(blank=True, default='', max_length=24)),
                ('stripe_id', models.CharField(blank=True, max_length=256)),
                ('subscr_id', models.CharField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
