# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/default/default_avatar.png', upload_to='images'),
        ),
    ]
