# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscr_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
