# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_subscr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('ARTIST', 'Artist'), ('CUSTOMER', 'Customer')], default='', max_length=24),
        ),
    ]
