# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DurationField(default=''),
        ),
    ]
