# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20200108_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DurationField(),
        ),
    ]
