# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200108_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
    ]
