# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-21 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20200121_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
    ]
