# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20200123_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.Painting'),
        ),
    ]
