# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-13 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20200301_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting', to='paintings.Painting'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
