# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auto_20200413_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='min_price',
            field=models.IntegerField(default='<django.db.models.fields.IntegerField>'),
        ),
    ]
