# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_auto_20200413_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
