# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(default='', max_length=64),
        ),
    ]
