# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-12 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_models', '0003_auto_20200412_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target_id',
            new_name='object_id',
        ),
    ]
