# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-13 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_models', '0004_auto_20200412_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
