# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(default='/default/default_img.jpg', upload_to='images')),
                ('bio', models.TextField(blank=True)),
                ('born_year', models.IntegerField(blank=True)),
                ('deceased_year', models.IntegerField(blank=True)),
                ('owner', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
