# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(default='/default/default_img.jpg', upload_to='images')),
                ('bio', models.TextField(blank=True)),
                ('born_year', models.IntegerField(blank=True)),
                ('deceased_year', models.IntegerField(blank=True)),
            ],
        ),
    ]
