# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20200407_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
