# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20200407_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='born_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='deceased_year',
            field=models.IntegerField(),
        ),
    ]
