# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20200407_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='born_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='deceased_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
