# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_auto_20200407_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='born_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='deceased_year',
            field=models.IntegerField(null=True),
        ),
    ]
