# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bio', models.TextField(blank=True, null=True)),
                ('born_year', models.IntegerField(blank=True, default=False, null=True)),
                ('deceased_year', models.IntegerField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('size', models.CharField(choices=[('', '---------'), ('SMALL', 'Small'), ('SMALL', 'Medium'), ('SMALL', 'Large')], default='', max_length=24)),
                ('price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('availability', models.BooleanField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.Artist')),
                ('artist_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='painting',
            name='subject',
            field=models.ManyToManyField(to='paintings.Subject'),
        ),
        migrations.AddField(
            model_name='painting',
            name='trend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.Trend'),
        ),
    ]
