# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
