# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
        migrations.AlterModelOptions(
            name='painting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trend',
            options={},
        ),
        migrations.RemoveField(
            model_name='painting',
            name='subjects',
        ),
        migrations.AddField(
            model_name='painting',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paintings.Subject'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='size',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('SMALL', 'Medium'), ('SMALL', 'Large')], default='', max_length=24),
        ),
    ]
