# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20191120_1233'),
        ('paintings', '0002_auto_20200407_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
        ),
    ]
