# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_auto_20191106_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='/default/default_img.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='born_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='deceased_year',
            field=models.IntegerField(blank=True),
        ),
    ]
