# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_auto_20191107_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
