# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_auto_20200407_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='trend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.Trend'),
        ),
    ]
