# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paintings', '0005_auto_20200407_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='availability',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.Media'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trend',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
