# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_auto_20200407_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='painting',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='painting',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
