# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paintings', '0008_auto_20200407_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('painting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='paintings.Painting')),
                ('user', models.ManyToManyField(related_name='users_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='paintings.Painting')),
                ('users', models.ManyToManyField(related_name='users_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
